# Generated by Django 4.1.5 on 2023-01-24 04:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("rooms", "0003_alter_amenity_options"),
    ]

    operations = [
        migrations.AddField(
            model_name="amenity",
            name="details",
            field=models.CharField(blank=True, default="", max_length=250),
        ),
        migrations.AddField(
            model_name="room",
            name="details",
            field=models.CharField(blank=True, default="", max_length=250),
        ),
        migrations.AlterField(
            model_name="amenity",
            name="description",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AlterField(
            model_name="amenity",
            name="name",
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name="room",
            name="description",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AlterField(
            model_name="room",
            name="name",
            field=models.CharField(max_length=100),
        ),
    ]
