# Generated by Django 4.1.5 on 2023-01-22 06:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('houses', '0002_house_pets_allowed'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='house',
            name='price',
        ),
        migrations.AddField(
            model_name='house',
            name='price_per_night',
            field=models.PositiveIntegerField(default=1, verbose_name='price'),
        ),
    ]
