# Generated by Django 4.1.5 on 2023-01-22 06:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('houses', '0003_remove_house_price_house_price_per_night'),
    ]

    operations = [
        migrations.AlterField(
            model_name='house',
            name='price_per_night',
            field=models.PositiveIntegerField(verbose_name='price'),
        ),
    ]
